# Generated by Django 5.1.1 on 2025-05-30 03:56

import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='شغل')),
                ('name_and_family', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_personel', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیم متخصص',
                'verbose_name_plural': 'تیم متخصص',
            },
        ),
        migrations.CreateModel(
            name='PersonelSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(blank=True, choices=[('email', 'email'), ('instagram', 'instagram'), ('linkedin', 'linkedin')], max_length=255, null=True, verbose_name='سایت')),
                ('media_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personel_social_media', to='personel.personel', verbose_name='تیم متخصص')),
            ],
            options={
                'verbose_name': 'آدرس شبکه های اجتماعی',
                'verbose_name_plural': 'آدرس شبکه های اجتماعی',
            },
        ),
    ]
