# Generated by Django 5.1.1 on 2025-06-01 12:57

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0002_alter_personel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر'),
        ),
    ]
