# Generated by Django 5.1.1 on 2025-05-29 17:52

import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title1', models.CharField(blank=True, max_length=500, null=True, verbose_name='متن اول')),
                ('slider_title2', models.CharField(blank=True, max_length=500, null=True, verbose_name='متن دوم')),
                ('slider_title3', models.CharField(blank=True, max_length=500, null=True, verbose_name='متن سوم')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.create_address, verbose_name='تصویر اسلایدر')),
                ('slider_link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='وضعیت فعال/غیرفعال')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
