# Generated by Django 5.1.1 on 2025-06-07 14:55

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sliders_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliders',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.create_address, verbose_name='تصویر اسلایدر'),
        ),
    ]
