# Generated by Django 5.1.1 on 2025-06-08 11:50

import ckeditor_uploader.fields
import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_sliders_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=500, null=True, verbose_name='سرتیتر')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='عنوان')),
                ('introduction', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='معرفی سایت')),
            ],
            options={
                'verbose_name': 'معرفی سایت',
                'verbose_name_plural': 'معرفی سایت',
            },
        ),
        migrations.AlterField(
            model_name='sliders',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.create_address, verbose_name='تصویر اسلایدر'),
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.indexintroduction', verbose_name='امکانات')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی ها',
            },
        ),
    ]
