# Generated by Django 5.1.1 on 2025-06-08 12:23

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_indexintroduction_alter_sliders_image_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='نام ویژگی'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.create_address, verbose_name='تصویر اسلایدر'),
        ),
    ]
