# Generated by Django 5.1.1 on 2025-06-08 12:59

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_properties_name_alter_sliders_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexintroduction',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='مدیا'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.create_address, verbose_name='تصویر اسلایدر'),
        ),
    ]
