# Generated by Django 5.1.1 on 2025-06-08 14:25

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_indexintroduction_image_alter_sliders_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexintroduction',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='مدیا'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='properties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propertiess', to='main.indexintroduction', verbose_name='امکانات'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.create_address, verbose_name='تصویر اسلایدر'),
        ),
    ]
