# Generated by Django 5.1.1 on 2025-07-23 22:12

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_indexintroduction_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexintroduction',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='مدیا'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.create_address, verbose_name='تصویر اسلایدر'),
        ),
    ]
