# Generated by Django 5.1.1 on 2025-05-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email1', models.EmailField(blank=True, default='', max_length=50, verbose_name='ایمیل ۱')),
                ('email2', models.EmailField(blank=True, default='', max_length=50, verbose_name='ایمیل ۲')),
                ('mobile_number1', models.CharField(blank=True, default='', max_length=13, verbose_name='شماره موبایل ۱')),
                ('mobile_number2', models.CharField(blank=True, default='', max_length=13, verbose_name='شماره موبایل ۲')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='آدرس کلینیک')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس کلینیک',
                'verbose_name_plural': 'اطلاعات تماس\u200c کلینیک',
            },
        ),
        migrations.CreateModel(
            name='WorkingTimesType1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنجشنبه', 'پنجشنبه'), ('جمعه', 'جمعه')], max_length=10, null=True, verbose_name='روز')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='زمان پایان')),
            ],
            options={
                'verbose_name': 'ساعت کاری',
                'verbose_name_plural': 'ساعات کاری',
            },
        ),
        migrations.CreateModel(
            name='WorkingTimeType2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=30, null=True, verbose_name='روز')),
                ('time_state', models.CharField(blank=True, default='', max_length=20, verbose_name='زمان شروع')),
            ],
            options={
                'verbose_name': 'ساعت کاری مدل 2',
                'verbose_name_plural': 'ساعات کاری مدل 2',
            },
        ),
    ]
