# Generated by Django 5.1.1 on 2025-05-13 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'پیام های بازدیدکنندگان و کاربران', 'verbose_name_plural': 'پیام های بازدیدکنندگان و کاربران'},
        ),
    ]
