# Generated by Django 5.0.6 on 2025-04-30 17:49

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mobile_number', models.CharField(max_length=11, unique=True)),
                ('unique_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('family', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('', 'انتخاب نشده'), ('مرد', 'مرد'), ('زن', 'زن')], default='', max_length=50, null=True)),
                ('registered_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
