# Generated by Django 5.1.1 on 2025-05-03 22:48

import ckeditor_uploader.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesandRegulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_and_conditions', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='قوانین و مقررات')),
                ('registered_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='اخرین بازدید')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'قوانین و مقررات',
                'verbose_name_plural': 'قوانین و مقررات',
            },
        ),
        migrations.CreateModel(
            name='Customuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mobile_number', models.CharField(help_text='لطفا شماره موبایل خود را درست وارد فرمائید', max_length=13, unique=True, verbose_name='شماره موبایل')),
                ('unique_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='ایمیل')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='نام')),
                ('family', models.CharField(blank=True, max_length=50, verbose_name='نام خانوادگی')),
                ('gender', models.CharField(blank=True, choices=[('', 'انتخاب نشده'), ('مرد', 'مرد'), ('زن', 'زن')], default='', max_length=50, null=True, verbose_name='جنسیت')),
                ('registered_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربران و پرسنل',
                'verbose_name_plural': 'کاربران و پرسنل',
            },
        ),
    ]
