# Generated by Django 5.1.1 on 2025-05-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesandRegulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_and_conditions', models.TextField(blank=True, null=True, verbose_name='قوانین و مقررات')),
                ('registered_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='اخرین بازدید')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'قوانین و مقررات',
                'verbose_name_plural': 'قوانین و مقررات',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'کاربران و پرسنل', 'verbose_name_plural': 'کاربران و پرسنل'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='family',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'انتخاب نشده'), ('مرد', 'مرد'), ('زن', 'زن')], default='', max_length=50, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(help_text='لطفا شماره موبایل خود را درست وارد فرمائید', max_length=13, unique=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام'),
        ),
    ]
