# Generated by Django 5.1.1 on 2025-05-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcode',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
