# Generated by Django 5.1.1 on 2025-05-01 20:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rulesandregulations_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesandregulations',
            name='rules_and_conditions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='قوانین و مقررات'),
        ),
    ]
