# Generated by Django 5.1.1 on 2025-05-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email1', models.EmailField(blank=True, max_length=50, null=True, verbose_name='ایمیل ۱')),
                ('email2', models.EmailField(blank=True, max_length=50, null=True, verbose_name='ایمیل ۲')),
                ('mobile_number1', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره موبایل ۱')),
                ('mobile_number2', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره موبایل ۲')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='آدرس کلینیک')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس\u200cها',
            },
        ),
    ]
