# Generated by Django 5.1.1 on 2025-05-12 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'اطلاعات تماس کلینیک', 'verbose_name_plural': 'اطلاعات تماس\u200c کلینیک'},
        ),
        migrations.AddField(
            model_name='contact',
            name='close_hour',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 12, 1, 54, 58, 801073), null=True, verbose_name='زمان اتمام فعالیت کلینیک'),
        ),
        migrations.AddField(
            model_name='contact',
            name='open_hour',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 12, 1, 54, 58, 801073), null=True, verbose_name='زمان شروع فعالیت کلینیک'),
        ),
    ]
