# Generated by Django 5.1.1 on 2025-05-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_options_contact_close_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='close_hour',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='open_hour',
        ),
    ]
