# Generated by Django 5.1.1 on 2025-05-07 19:53

import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='ظرفیت نوبت'),
        ),
        migrations.AddField(
            model_name='services',
            name='finish_reservation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان نوبت دهی'),
        ),
        migrations.AddField(
            model_name='services',
            name='is_available',
            field=models.BooleanField(blank=True, null=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AddField(
            model_name='services',
            name='start_reservation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع نوبت دهی'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر خدمات'),
        ),
    ]
