# Generated by Django 5.1.1 on 2025-05-09 13:39

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_services_capacity_services_finish_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر خدمات'),
        ),
        migrations.CreateModel(
            name='ServiceFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, verbose_name='نام ویژگی')),
                ('feature_value', models.CharField(max_length=255, verbose_name='مقدار ویژگی')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.services', verbose_name='خدمات مرتبط')),
            ],
            options={
                'verbose_name': 'ویژگی خدمات',
                'verbose_name_plural': 'ویژگی\u200cهای خدمات',
            },
        ),
    ]
