# Generated by Django 5.1.1 on 2025-05-09 16:53

import ckeditor.fields
import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_services_service_image_servicefeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='proper_candidate_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='شرح کوتاه'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر خدمات'),
        ),
        migrations.CreateModel(
            name='ServiceAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage_name', models.CharField(max_length=100, verbose_name='نام مزیت')),
                ('advantage_value', models.CharField(max_length=255, verbose_name='صفت مزیت')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='services.services', verbose_name='مزایای این سرویس')),
            ],
            options={
                'verbose_name': 'مزایای خدمات',
                'verbose_name_plural': 'مزایای خدمات',
            },
        ),
        migrations.CreateModel(
            name='ServiceCandidateCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=400, verbose_name='شرایط')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='services.services', verbose_name='شرایط استفاده کننده از این سرویس')),
            ],
            options={
                'verbose_name': 'مزایای خدمات',
                'verbose_name_plural': 'مزایای خدمات',
            },
        ),
    ]
