# Generated by Django 5.1.1 on 2025-05-09 17:21

import ckeditor.fields
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_services_proper_candidate_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='proper_candidate_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='شرح شرایط کاندید'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر خدمات'),
        ),
    ]
