# Generated by Django 5.1.1 on 2025-05-09 22:19

import ckeditor.fields
import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_services_proper_candidate_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecandidatecondition',
            options={'verbose_name': 'شرایط استفاده از این خدمات', 'verbose_name_plural': 'شرایط استفاده از این خدمات'},
        ),
        migrations.AddField(
            model_name='services',
            name='procedure_یثسزقهحفهخد',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='شرح مراحل این سرویس '),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر خدمات'),
        ),
        migrations.CreateModel(
            name='ServiceProcedures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=500, verbose_name='مراحل')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='services.services', verbose_name='پروسه')),
            ],
            options={
                'verbose_name': 'مراحل استفاده از این خدمات',
                'verbose_name_plural': 'مراحل استفاده از این خدمات',
            },
        ),
    ]
