# Generated by Django 5.1.1 on 2025-05-09 22:21

import ckeditor.fields
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_servicecandidatecondition_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='procedure_یثسزقهحفهخد',
        ),
        migrations.AddField(
            model_name='services',
            name='procedure_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='شرح کلی پروسه این سرویس '),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر خدمات'),
        ),
    ]
