# Generated by Django 5.1.1 on 2025-05-10 01:52

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_services_procedure_یثسزقهحفهخد_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprocedures',
            name='process_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام مراحل'),
        ),
        migrations.AlterField(
            model_name='serviceadvantages',
            name='advantage_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مزیت'),
        ),
        migrations.AlterField(
            model_name='serviceadvantages',
            name='advantage_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='صفت مزیت'),
        ),
        migrations.AlterField(
            model_name='servicecandidatecondition',
            name='condition',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='شرایط'),
        ),
        migrations.AlterField(
            model_name='servicefeatures',
            name='feature_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام ویژگی'),
        ),
        migrations.AlterField(
            model_name='servicefeatures',
            name='feature_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مقدار ویژگی'),
        ),
        migrations.AlterField(
            model_name='serviceprocedures',
            name='process',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیح مراحل'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر خدمات'),
        ),
    ]
