# Generated by Django 5.1.1 on 2025-05-11 19:04

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_services_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر خدمات'),
        ),
        migrations.CreateModel(
            name='ServiceRecurringQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_questions', to='services.services', verbose_name='سوالات متداول درباره ی این سرویس')),
            ],
            options={
                'verbose_name': 'سوال متداول سرویس',
                'verbose_name_plural': 'سوالات متداول سرویس',
            },
        ),
    ]
