# Generated by Django 5.1.1 on 2025-05-11 19:26

import ckeditor.fields
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_services_service_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecurringquestion',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر خدمات'),
        ),
    ]
