# Generated by Django 5.1.1 on 2025-05-12 16:41

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_alter_services_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر خدمات'),
        ),
    ]
