# Generated by Django 5.1.1 on 2025-07-29 17:38

import django.utils.timezone
import django_jalali.db.models
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0079_alter_services_service_image_alter_services_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='finish_reservation_date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='تاریخ پایان نوبت دهی'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر خدمات'),
        ),
        migrations.AlterField(
            model_name='services',
            name='start_reservation_date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع نوبت دهی'),
        ),
    ]
