"""
Django settings for royal_clinic project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&8l5=ud(ys$%o^9w$dc$=6xi9c^al)j=si8kea(v^+!a5no&h3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 'jazzmin',
    'django.contrib.admin',
    
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'django_admin_listfilter_dropdown',
    
    'ckeditor',
    'ckeditor_uploader',
    
    
    'django_jalali',
    'django.contrib.humanize',
    
    'django_render_partial', 
    
    'apps.main.apps.MainConfig',
    'apps.accounts.apps.AccountsConfig',
    'apps.services.apps.ServicesConfig',
    'apps.user_services.apps.UserServicesConfig',
    'apps.comments_scores_favourites.apps.CommentsScoresFavouritesConfig',
    'apps.contact.apps.ContactConfig',
    'apps.search.apps.SearchConfig',
    
    'jalali_date', 
    'apps.patient_panel.apps.PatientPanelConfig',
    
    'apps.reservation.apps.ReservationConfig',
    'apps.realtime_chat.apps.RealtimeChatConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'middlewares.middlewares.SessionSecurityMiddleware',
    

    
]



JALALI_DATE_DEFAULTS = {
    'LIST_DISPLAY_AUTO_CONVERT': False,
    'Strftime': {
        'date': '%y/%m/%d',
        'datetime': '%H:%M:%S _ %y/%m/%d',
    },
    'Static': {
        'js': [
            'admin/js/django_jalali.min.js',
        ],
        'css': {
            'all': [
                'admin/css/django_jalali.min.css',
            ]
        }
    },
}



ROOT_URLCONF = 'royal_clinic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.main.views.media_admin',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'royal_clinic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE' : 'django.db.backends.mysql',
        'NAME' : 'royal_clinic',
        'USER' : 'root',
        'PASSWORD' : '1375sunny1375',
        'HOST' : 'localhost' ,
        'PORT' : '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'
USE_TZ = True

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media/')

STATIC_URL = '/static/'
STATICFILES_DIRS =  (os.path.join(BASE_DIR,'static/'),)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------------------------------------------------------------------------------
# define CustomUser to the system

AUTH_USER_MODEL = "accounts.Customuser"
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']
# ------------------------------------------------------------------------------------------
# DjangoJazmin settings

JAZZMIN_SETTINGS = {

    "custom_css": "css/custom_admin.css",
    "show_sidebar": True,
    "navigation_expanded": True,
    "changeform_format": "horizontal_tabs",  # یا 'collapsible' یا 'single'

}


# -----------------------------------------------------------------------------------------
# تنظیمات سیکاادیتور
CKEDITOR_UPLOAD_PATH = "ckeditor/uploads/"

CKEDITOR_CONFIGS = {
    

    'default' :
        {
            
            'toolbar' : 'Custom',
            'toolbar_custom' : [
                ['Bold','link','Unlink','Image'],
            ],
            
        },
    
    'special' :
        {
            
           'toolbar' : 'special', 'height' : 500, 'toolbar' : 'full',
            'toolbar_Special' : [
                ['Bold','link','Unlink','Image'],
                ['CodeSnippet'],
            ], 
            
            'extraPlugins' : ','.join(['codesnippet','clipboard',])
            
        },
        
    'special_an' :
        {
            'toolbar' : 'Special' , 'height' : 500,
            'toolbar_Special' : 
                [
                    ['Bold'],
                    ['CodeSnippet'],
                ],
                'extraPlugins' : ','.join(['codesnippet',])
        }
    
    }

# ------------------------------------------------------------------------
