# Generated by Django 5.1.1 on 2025-05-30 22:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0065_alter_services_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان تخفیف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('discount_percentage', models.PositiveIntegerField(blank=True, null=True, verbose_name='درصد تخفیف')),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='شروع تخفیف')),
                ('end_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='پایان تخفیف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ManyToManyField(related_name='discounts', to='services.services', verbose_name='سرویس مربوطه')),
            ],
            options={
                'verbose_name': 'تخفیف خدمات',
                'verbose_name_plural': 'تخفیف\u200cهای خدمات',
                'ordering': ['-start_date'],
            },
        ),
    ]
