# Generated by Django 5.1.1 on 2025-07-30 18:51

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicediscount',
            name='end_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='پایان تخفیف'),
        ),
        migrations.AlterField(
            model_name='servicediscount',
            name='start_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='شروع تخفیف'),
        ),
    ]
