# Generated by Django 5.1.1 on 2025-05-10 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0010_alter_services_service_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='متن نظر')),
                ('registerdate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج نظر')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت نظر')),
                ('approving_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_user2', to=settings.AUTH_USER_MODEL, verbose_name='کاربر تایید کننده نظر')),
                ('comment_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_child', to='comments_scores_favourites.comment', verbose_name='والد نظر')),
                ('commenting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_user1', to=settings.AUTH_USER_MODEL, verbose_name='کاربر نظر دهنده')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_comments', to='services.services', verbose_name='سرویس مربوطه')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
