# Generated by Django 5.1.1 on 2025-05-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_scores_favourites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_admin_comment',
            field=models.BooleanField(default=False, verbose_name='نظر توسط ادمین'),
        ),
    ]
