# Generated by Django 5.1.1 on 2025-07-23 22:12

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_scores_favourites', '0003_addscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addscore',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='registerdate',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ درج نظر'),
        ),
    ]
