# Generated by Django 5.1.1 on 2025-05-13 01:02

import django.db.models.deletion
import django.utils.timezone
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_activationcode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPatient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('birth_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ تولد')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('O+', 'O+'), ('O-', 'O-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True, verbose_name='گروه خونی')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='وزن')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='قد')),
                ('emergency_contact', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس اضطراری')),
                ('image_name', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر پروفایل')),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان حساسیت')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patient_panel.custompatient', verbose_name='بیمار')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بیماری یا سابقه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history_items', to='patient_panel.custompatient', verbose_name='بیمار')),
            ],
        ),
    ]
