# Generated by Django 5.1.1 on 2025-05-14 01:31

import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'verbose_name': 'حساسیت', 'verbose_name_plural': 'حساسیت ها'},
        ),
        migrations.AlterModelOptions(
            name='custompatient',
            options={'verbose_name': 'بیمار', 'verbose_name_plural': 'بیماران'},
        ),
        migrations.AlterModelOptions(
            name='medicalhistoryitem',
            options={'verbose_name': 'بیماری یا سابقه', 'verbose_name_plural': 'بیماری یا سابقه'},
        ),
        migrations.AddField(
            model_name='medicalhistoryitem',
            name='diagnosis_year',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ تشخیص'),
        ),
        migrations.AlterField(
            model_name='custompatient',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر پروفایل'),
        ),
    ]
