# Generated by Django 5.1.1 on 2025-05-14 15:23

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_panel', '0002_alter_allergy_options_alter_custompatient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompatient',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='قد بیمار به سانتی\u200cمتر', null=True, verbose_name='قد (سانتی\u200cمتر)'),
        ),
        migrations.AlterField(
            model_name='custompatient',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='custompatient',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='وزن بیمار به کیلوگرم', null=True, verbose_name='وزن (کیلوگرم)'),
        ),
    ]
