# Generated by Django 5.1.1 on 2025-05-14 16:03

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_panel', '0003_alter_custompatient_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompatient',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='مثال: 09123456789 یا 021-123456789', max_length=11, null=True, verbose_name='شماره تماس اضطراری'),
        ),
        migrations.AlterField(
            model_name='custompatient',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر پروفایل'),
        ),
    ]
