# Generated by Django 5.1.1 on 2025-05-14 23:11

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_panel', '0004_alter_custompatient_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompatient',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='021-12345678', max_length=13, null=True, verbose_name='شماره تماس اضطراری'),
        ),
        migrations.AlterField(
            model_name='custompatient',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر پروفایل'),
        ),
    ]
