# Generated by Django 5.1.1 on 2025-05-14 23:58

import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_panel', '0005_alter_custompatient_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompatient',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='medicalhistoryitem',
            name='diagnosis_year',
            field=models.IntegerField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ تشخیص'),
        ),
    ]
