# Generated by Django 5.1.1 on 2025-05-26 23:46

import django.db.models.deletion
import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_panel', '0014_alter_custompatient_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompatient',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر پروفایل'),
        ),
        migrations.CreateModel(
            name='CurrentMedications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام دارو')),
                ('dosage', models.CharField(blank=True, max_length=100, null=True, verbose_name='دوز مصرف')),
                ('priscribed_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ شروع مصرف')),
                ('using_state', models.CharField(choices=[('still_using', 'still_using'), ('stopped', 'stopped')], default='still_using', max_length=20, verbose_name='وضعیت استفاده')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patient_panel.custompatient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'دارو',
                'verbose_name_plural': 'داروها',
            },
        ),
    ]
