# Generated by Django 5.1.1 on 2025-05-27 17:19

import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_panel', '0016_alter_currentmedications_priscribed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentmedications',
            name='priscribed_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ شروع مصرف'),
        ),
        migrations.AlterField(
            model_name='custompatient',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر پروفایل'),
        ),
    ]
