# Generated by Django 5.1.1 on 2025-05-29 01:45

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_panel', '0017_alter_currentmedications_priscribed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowPatientPanelForAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'نمایش پنل و اطلاعات بیماران',
                'verbose_name_plural': 'نمایش پنل و اطلاعات بیماران',
            },
        ),
        migrations.AlterField(
            model_name='currentmedications',
            name='using_state',
            field=models.CharField(choices=[('در حال استفاده', 'در حال استفاده'), ('مصرف تمام شده', 'مصرف تمام شده')], default='still_using', max_length=20, verbose_name='وضعیت استفاده'),
        ),
        migrations.AlterField(
            model_name='custompatient',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر پروفایل'),
        ),
        migrations.CreateModel(
            name='DrRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dr_recommendations', to='patient_panel.custompatient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'پیشنهادات دکتر',
                'verbose_name_plural': 'پیشنهادات دکتر',
            },
        ),
    ]
