# Generated by Django 5.1.1 on 2025-05-29 14:39

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_panel', '0018_showpatientpanelforadmin_and_more'),
        ('services', '0061_alter_services_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='drrecommendations',
            name='recommended_services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dr_recommendations', to='services.services', verbose_name='خدمات پیشنهادی'),
        ),
        migrations.AlterField(
            model_name='custompatient',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر پروفایل'),
        ),
    ]
