# Generated by Django 5.1.1 on 2025-07-31 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلانات'},
        ),
    ]
