# Generated by Django 5.1.1 on 2025-06-01 12:57

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0066_alter_services_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان ویدیو')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('video_file', models.FileField(upload_to=utils.FileUpload.create_address, verbose_name='فایل ویدیو')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر شاخص')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='services.services', verbose_name='سرویس مربوطه')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیوها',
            },
        ),
    ]
