# Generated by Django 5.1.1 on 2025-07-23 21:47

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_alter_servicevideo_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='video_file',
            field=models.FileField(upload_to=utils.FileUpload.create_address, verbose_name='فایل ویدیو'),
        ),
    ]
