# Generated by Django 5.1.1 on 2025-07-23 23:55

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_alter_servicevideo_thumbnail_and_more'),
        ('services', '0078_alter_services_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='video_file',
            field=models.FileField(upload_to=utils.FileUpload.create_address, verbose_name='فایل ویدیو'),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان تصویر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image_file', models.ImageField(upload_to=utils.FileUpload.create_address, verbose_name='فایل تصویر')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.services', verbose_name='سرویس مربوطه')),
            ],
        ),
    ]
