# Generated by Django 5.1.1 on 2025-07-24 03:23

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_alter_servicevideo_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image_file',
            field=models.ImageField(upload_to=utils.FileUpload.create_address, verbose_name='فایل تصویر'),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='video_file',
            field=models.FileField(upload_to=utils.FileUpload.create_address, verbose_name='فایل ویدیو'),
        ),
    ]
