# Generated by Django 5.1.1 on 2025-07-30 00:36

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_alter_serviceimage_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='image_file',
            field=models.ImageField(upload_to=utils.FileUpload.create_address, verbose_name='فایل تصویر'),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.create_address, verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='video_file',
            field=models.FileField(upload_to=utils.FileUpload.create_address, verbose_name='فایل ویدیو'),
        ),
    ]
