# Generated by Django 5.1.1 on 2025-05-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reserveappointment_selected_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveappointment',
            name='selected_date',
            field=models.CharField(max_length=10, verbose_name='تاریخ انتخاب'),
        ),
    ]
