# Generated by Django 5.1.1 on 2025-06-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reserveappointment_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveappointment',
            name='selected_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ انتخاب'),
        ),
    ]
