# Generated by Django 5.1.1 on 2025-07-30 00:36

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reserveappointment_selected_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveappointment',
            name='selected_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ انتخاب\u200c شده'),
        ),
    ]
